SELECT * FROM (
SELECT CONCAT(CONCAT(CONCAT(NAME,'('),SUBSTR(OCCUPATION,1,1)),')') AS "COLUMN" 
FROM OCCUPATIONS
ORDER BY NAME) T1
UNION
SELECT * FROM (
SELECT CONCAT(CONCAT(CONCAT(CONCAT('There are a total of ',COUNT(OCCUPATION)),' '),LOWER(OCCUPATION)),'s.') AS "COLUMN" 
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(OCCUPATION),OCCUPATION);
